# Generated by Django 5.2 on 2025-04-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="task_manager.label"
            ),
        ),
    ]
