# Generated by Django 5.2 on 2025-04-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0006_alter_status_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date Created"
            ),
        ),
    ]
